### ISSUE TITLE
Create a PyPI package

### ISSUE THREAD

**Issue by travishathaway** [conda-incubator/conda-sphinx-theme#1]
### What is the idea?

We need to package this theme and upload it to PyPI.

**Comment by jezdez** [comment]
So PyPI [supports trusted publishers since recently](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/), and I think we should make use of it. Here are the docs [how to make use of them](https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/).

We have a conda organization on PyPI, once the project is created, we can add it to the organization.

**Comment by travishathaway** [comment]
@jezdez,

We have a PyPI package and a GitHub action that will automatically update it after we create a release here:

- https://pypi.org/project/conda-sphinx-theme/
- https://github.com/conda-incubator/conda-sphinx-theme/blob/main/.github/workflows/release.yml
